---
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: argocd-tanka-plugin
spec:
  version: "1.0"
  init:
    command: ["/init.sh"]
  generate:
    command: ["/generate.sh"]
